/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Clorio Data API
 * OpenAPI spec version: 1.0.0
 */

export interface GetAccount {
  balance: string;
  nonce: number;
  /** @nullable */
  delegate: string | null;
}
