/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Clorio Data API
 * OpenAPI spec version: 1.0.0
 */
import type { GetMinaInfoRemainingTime } from './getMinaInfoRemainingTime';

export interface GetMinaInfo {
  epoch: number;
  slot: number;
  height: number;
  remainingTime: GetMinaInfoRemainingTime;
  error?: boolean;
  errorMessage?: string;
}
