/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Clorio Data API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTickerMina } from './getTickerMina';

export interface GetTicker {
  mina: GetTickerMina;
}
